Modify rebuild-scratch-org
Updated rebuild-scratch-org shell script to move most logic into functions.  This way, the script that drives the rebuild process (starting at line 189) is easier to read and understand.

diff --git a/dev-tools/rebuild-scratch-org b/dev-tools/rebuild-scratch-org
--- a/dev-tools/rebuild-scratch-org
+++ b/dev-tools/rebuild-scratch-org
@@ -12,7 +12,13 @@
 # INSTRUCTIONS: Execute the following command from the root of your SFDX project directory.
 #               ./dev-tools/rebuild-scratch-org
 #
+####################################################################################################
+#
+##
+###
 #### LOAD SHARED FUNCTIONS LIBRARY #################################################################
+###
+##
 #
 if [ ! -r `dirname $0`/lib/shared-functions.sh ]; then
   echo "\nFATAL ERROR: `tput sgr0``tput setaf 1`Could not load dev-tools/lib/shared-functions.sh.  File not found.\n"
@@ -20,86 +26,198 @@ if [ ! -r `dirname $0`/lib/shared-functions.sh ]; then
 fi
 source `dirname $0`/lib/shared-functions.sh
 #
-#
+##
+###
 #### CONFIRM SCRIPT EXECUTION ######################################################################
+###
+##
 #
 confirmScriptExecution "Do you want to rebuild your scratch org?"
 #
-#
+##
+###
 #### CREATE LOCAL VARIABLES ########################################################################
+###
+##
 #
 # No local variables are used by this script.
 #
+##
+###
+#### FUNCTION: deleteScratchOrg () #################################################################
+###
+##
 #
+deleteScratchOrg () {
+  # Delete the current scratch org.
+  echoStepMsg "Delete the $SCRATCH_ORG_ALIAS scratch org"
+  echo "Executing force:org:delete -p -u $SCRATCH_ORG_ALIAS -v $DEV_HUB_ALIAS" 
+  (cd $PROJECT_ROOT && exec sfdx force:org:delete -p -u $SCRATCH_ORG_ALIAS -v $DEV_HUB_ALIAS )
+}
+#
+##
+###
+#### FUNCTION: validateScratchOrgDeletion () #######################################################
+###
+##
+#
+validateScratchOrgDeletion () {
+  # Confirm that the scratch org is no longer the default username in SFDX local config.
+  echoStepMsg "Validate deletion of the scratch org"
+  echo "Executing sfdx force:config:list to confirm deletion from project local config"
+  (cd $PROJECT_ROOT && exec sfdx force:config:list)
+}
+#
+##
+###
+#### FUNCTION: createScratchOrg () #################################################################
+###
+##
+#
+createScratchOrg() {
+  # Create a new scratch org using the scratch-def.json locally configured for this project. 
+  echoStepMsg "Create a new $SCRATCH_ORG_ALIAS scratch org"
+  echo "Executing force:org:create -f $SCRATCH_ORG_CONFIG -a $SCRATCH_ORG_ALIAS -v $DEV_HUB_ALIAS -s -d 29"
+  (cd $PROJECT_ROOT && exec sfdx force:org:create -f $SCRATCH_ORG_CONFIG -a $SCRATCH_ORG_ALIAS -v $DEV_HUB_ALIAS -s -d 29)
+  if [ $? -ne 0 ]; then
+    echoErrorMsg "Scratch org could not be created. Aborting Script."
+    exit 1
+  fi
+}
+#
+##
+###
+#### FUNCTION: installPackage () ###################################################################
+###
+##
+#
+installPackage () {
+  echoStepMsg "$3"
+
+  # Print the time (HH:MM:SS) when the installation started.
+  echo "Executing force:package:install -i $1 -p 5 -w 10 -u $SCRATCH_ORG_ALIAS"
+  echo "\n`tput bold`Package installation started at `date +%T``tput sgr0`\n"
+  local startTime=`date +%s`
+
+  # Perform the package installation.  If the installation fails abort the script.
+  (cd $DEMO_ROOT && exec sfdx force:package:install -i $1 -p 5 -w 10 -u $SCRATCH_ORG_ALIAS)
+  if [ $? -ne 0 ]; then
+    echoErrorMsg "$2 could not be installed. Aborting Script."
+    exit 1
+  fi
+
+  # Print the time (HH:MM:SS) when the installation completed.
+  echo "\n`tput bold`Package installation completed at `date +%T``tput sgr0`"
+  local endTime=`date +%s`
+
+  # Determine the total runtime (in seconds) and show the user.
+  local totalRuntime=$((endTime-startTime))
+  echo "Total runtime for package installation was $totalRuntime seconds."
+}
+#
+##
+###
+#### FUNCTION: pushMetadata () #####################################################################
+###
+##
+#
+pushMetadata () {
+  # Push metadata to the new Scratch Org.
+  echoStepMsg "Push metadata to the new scratch org"
+  echo "Executing force:source:push -u $SCRATCH_ORG_ALIAS"
+  (cd $PROJECT_ROOT && exec sfdx force:source:push -u $SCRATCH_ORG_ALIAS)
+  if [ $? -ne 0 ]; then
+    echoErrorMsg "SFDX source could not be pushed to the scratch org. Aborting Script."
+    exit 1
+  fi
+}
+#
+##
+###
+#### FUNCTION: assignPermset () ####################################################################
+###
+##
+#
+assignPermset () {
+  # Assign permission sets to the scratch org's Admin user.
+  echoStepMsg "Assign the $1 permission set to the scratch org's Admin user"
+  echo \
+  "Executing force:user:permset:assign \\
+              --permsetname "$1" \\
+              --targetusername $SCRATCH_ORG_ALIAS \\
+              --loglevel error\n"
+  (cd $PROJECT_ROOT && exec sfdx force:user:permset:assign \
+                                  --permsetname "$1" \
+                                  --targetusername $SCRATCH_ORG_ALIAS \
+                                  --loglevel error)
+  if [ $? -ne 0 ]; then
+    echoErrorMsg "Permission set \"$1\" could not be assigned to the admin user. Aborting Script."
+    exit 1
+  fi
+}
+#
+##
+###
+#### FUNCTION: importData () #######################################################################
+###
+##
+#
+importData () {
+  # Setup development data
+  echoStepMsg "Import data from $1"
+  echo \
+  "Executing force:data:tree:import \\
+              --plan \"$1\" \\
+              --targetusername $SCRATCH_ORG_ALIAS \\
+              --loglevel error)\n"
+  (cd $PROJECT_ROOT && exec sfdx force:data:tree:import \
+                                  --plan "$1" \
+                                  --targetusername $SCRATCH_ORG_ALIAS \
+                                  --loglevel error)
+  if [ $? -ne 0 ]; then
+    echoErrorMsg "Data import failed. Aborting Script."
+    exit 1
+  fi
+}
+#
+##
+###
 #### SCRATCH ORG SETUP (DELETE/CREATE/PUSH) ########################################################
+###
+##
 #
-# 0. Reset the Step Message counter and set the TOTAL STEPS to 4.
+# Reset the Step Message counter and set the TOTAL STEPS to 4.
 resetStepMsgCounter 4
 
-# 1. Delete the current scratch org.
-echoStepMsg "Delete the $SCRATCH_ORG_ALIAS scratch org"
-echo "Executing force:org:delete -p -u $SCRATCH_ORG_ALIAS -v $DEV_HUB_ALIAS" 
-(cd $PROJECT_ROOT && exec sfdx force:org:delete -p -u $SCRATCH_ORG_ALIAS -v $DEV_HUB_ALIAS )
+# Delete the current scratch org. (Step 1 and 2)
+deleteScratchOrg
 
-# 2. Confirm that the scratch org is no longer the default username in SFDX local config.
-echoStepMsg "Validate deletion of the scratch org"
-echo "Executing sfdx force:config:list to confirm deletion from project local config"
-(cd $PROJECT_ROOT && exec sfdx force:config:list)
+# Create a new scratch org using the scratch-def.json locally configured for this project. (Step 3)
+createScratchOrg
 
-# 3. Create a new scratch org using the scratch-def.json locally configured for this project. 
-echoStepMsg "Create a new $SCRATCH_ORG_ALIAS scratch org"
-echo "Executing force:org:create -f $SCRATCH_ORG_CONFIG -a $SCRATCH_ORG_ALIAS -v $DEV_HUB_ALIAS -s -d 29"
-(cd $PROJECT_ROOT && exec sfdx force:org:create -f $SCRATCH_ORG_CONFIG -a $SCRATCH_ORG_ALIAS -v $DEV_HUB_ALIAS -s -d 29)
-if [ $? -ne 0 ]; then
-  echoErrorMsg "Scratch org could not be created. Aborting Script."
-  exit 1
-fi
+# Install any packages (managed or unmanaged). (Step 4-???)
+# Template for calling this function:
+# installPackage #PACKAGE_VERSION_ID# \
+#                "#PACKAGE_NAME#" \
+#                "#STEP_MESSAGE#"
 
-# 4. Push metadata to the new Scratch Org.
-echoStepMsg "Push metadata to the new scratch org"
-echo "Executing force:source:push -u $SCRATCH_ORG_ALIAS"
-(cd $PROJECT_ROOT && exec sfdx force:source:push -u $SCRATCH_ORG_ALIAS)
-if [ $? -ne 0 ]; then
-  echoErrorMsg "SFDX source could not be pushed to the scratch org. Aborting Script."
-  exit 1
-fi
+# Push metadata to the new Scratch Org. (Step 4, unless there are installPackage() calls made)
+pushMetadata
 
-#### Uncomment and modify if you need to install permission sets
-# 5. Assign permission sets to the scratch org's Admin user.
-#echoStepMsg "Assign permission sets to the scratch org's Admin user"
-#echo \
-#"Executing force:user:permset:assign \\
-#            --permsetname "My_Permission_Set" \\
-#            --targetusername $SCRATCH_ORG_ALIAS \\
-#            --loglevel error\n"
-#(cd $PROJECT_ROOT && exec sfdx force:user:permset:assign \
-#                                --permsetname "My_Permission_Set" \
-#                                --targetusername $SCRATCH_ORG_ALIAS \
-#                                --loglevel error)
-#if [ $? -ne 0 ]; then
-#  echoErrorMsg "Permission set could not be assigned to the admin user. Aborting Script."
-#  exit 1
-#fi
+# Assign permission sets to the scratch org's Admin user. (Step 5, typically)
+# Template for calling this function:
+# assignPermset #PERMSET_NAME# 
 
-#### Uncomment and modify if you need to setup data in your scratch org.
-# 6. Setup development data
-#echoStepMsg "Setup/import data needed for development"
-#echo \
-#"Executing force:data:tree:import \\
-#            --plan ./data/dataplan.json \\
-#            --targetusername $SCRATCH_ORG_ALIAS \\
-#            --loglevel error)\n"
-#(cd $PROJECT_ROOT && exec sfdx force:data:tree:import \
-#                                --plan ./data/dataplan.json \
-#                                --targetusername $SCRATCH_ORG_ALIAS \
-#                                --loglevel error)
-#if [ $? -ne 0 ]; then
-#  echoErrorMsg "Development data could not be imported into the scratch org. Aborting Script."
-#  exit 1
-#fi
+# Import data used during development (Step 6, typically)
+# Template for calling this function:
+# importData "#DATA_TREE_PLAN_FILEPATH#"
+
 #
-#
+##
+###
 #### ECHO CLOSING MESSAGE ##########################################################################
+###
+##
 #
 echoScriptCompleteMsg \
 "Rebuild of scratch org $SCRATCH_ORG_ALIAS completed successfully."
